dist: bionic

sudo: required

language: minimal

env:
  global:
    - RELEASE_BRANCH="master"
  jobs:
    - INSTALLATIONN=1
    - INSTALLATIONN=2
    - INSTALLATIONN=3
    - INSTALLATIONN=4
    - INSTALLATIONN=5

install:
  - bash deployscript/install.sh "$INSTALLATIONN"
  - wget "https://raw.githubusercontent.com/ferion11/LogosLinuxInstaller/master/install_AppImageWine_and_Logos.sh"

script:
  - bash deployscript/deploy"$INSTALLATIONN".sh

after_success:
  # result
  - mkdir result
  - cp screenshots_"$INSTALLATIONN".tar.gz result/
  - cp video"$INSTALLATIONN".mp4 result/

  # md5sum tool
  - wget -c https://github.com/ferion11/libsutil/releases/download/md5sum_util_v0.1/md5sum_util.sh
  - bash md5sum_util.sh result

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh

  - |- # publish
    if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
      export UPLOADTOOL_BODY="Instructions can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    else
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    fi

after_failure:
  - echo 'Publishing failure release to GitHub...'
  - export UPLOADTOOL_SUFFIX="failure"
  - export UPLOADTOOL_BODY="Instructions can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***failure experimental build test*** for testing new features and debug.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
  - bash upload.sh result/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
