name: op5-Logos64wine2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test64wine2:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run the install.sh and preparations
      shell: bash
      run: |
        bash ./deployscript/install.sh 5
        wget "https://raw.githubusercontent.com/ferion11/LogosLinuxInstaller/master/install_AppImageWine_and_Logos.sh"

    - name: Run the deploy5.sh
      shell: bash
      run: bash ./deployscript/deploy5.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact5
        path: |
          screenshots_5.tar.gz
          video5.mp4
