name: opa-Logos64wine2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test64wine2A:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run the install.sh and preparations
      shell: bash
      run: |
        bash ./deployscript/install.sh a
        wget -c "https://raw.githubusercontent.com/ferion11/LogosLinuxInstaller/master/fast_install_AppImageWine_and_Logos.sh"

    - name: Run the deploy.sh a
      shell: bash
      run: bash ./deployscript/deploy.sh a

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacta
        path: |
          screenshots_a.tar.gz
          videoa.mp4
